import type { FieldSpec, SectionSpec } from "./registry";

type Text = { title?: string; label?: string; description?: string; reason?: string };

const sections: Record<string, Text> = {
  voz: { title: "Voice", description: "How Dax listens, responds, and decides who to obey." },
  inteligencia: { title: "Intelligence", description: "Which model thinks, its tool budget, and which providers handle failures." },
  capacidades: { title: "Capabilities", description: "What Dax can access: MCP servers, tool permissions, and shell binaries." },
  memoria: { title: "Memory", description: "What Dax knows about you and the instructions used at the start of every turn." },
  canales: { title: "Channels", description: "Other ways to talk to Dax." },
  acceso: { title: "Access", description: "Who can connect and through which interfaces." },
  sistema: { title: "System", description: "Identity, logs, data paths, and preferences for this app." },
};

const groups: Record<string, Text> = {
  "voz-estado": { title: "Status", description: "The live voice pipeline." },
  "voz-escucha": { title: "How Dax listens", description: "Wake word, microphone, and end-of-speech detection." },
  "voz-conversa": { title: "How Dax converses", description: "Turns, follow-up windows, and when a conversation ends." },
  "voz-habla": { title: "How Dax speaks", description: "Speech engine, per-language voices, and speed." },
  "voz-galeria": { title: "Voice gallery", description: "Preview available voices before choosing one." },
  "voz-transcribe": { title: "How Dax transcribes", description: "Local or hosted speech recognition." },
  "voz-quien": { title: "Who can speak", description: "Speaker verification." },
  "voz-perfil": { title: "Your voice profile", description: "Record samples so Dax recognizes your voice." },
  "int-enrutado": { title: "Routing and budget", description: "The active provider, fallback chain, and tool budget." },
  "int-ollama": { title: "Ollama", description: "Local models served by Ollama." },
  "int-codex": { title: "Codex", description: "The `codex exec` subprocess. Text only; it runs its own tool loop." },
  "cap-servidores": { title: "MCP servers", description: "Each server contributes tools to the agent." },
  "cap-politica": { title: "Tool permissions", description: "What runs, asks for confirmation, or is denied. Applied live." },
  "cap-shell": { title: "Allowed shell binaries", description: "The dax-system server only runs commands in this list." },
  "mem-prompt": { title: "System instructions", description: "The base prompt, applied to every channel." },
  "mem-ruta": { title: "Memory location" },
  "mem-archivos": { title: "Memory files", description: "Persistent notes the agent can read and write." },
  "can-telegram": { title: "Telegram", description: "Bidirectional long-polling bot. No public URL required." },
  "can-whatsapp": { title: "WhatsApp", description: "Through Evolution API, with incoming messages delivered by webhook." },
  "acc-cuenta": { title: "Password", description: "This server's only credential." },
  "acc-sesion": { title: "Session", description: "Authentication and session cookie lifetime." },
  "acc-red": { title: "Network", description: "Where the backend listens. Host and port require a restart." },
  "sis-identidad": { title: "Identity and language" },
  "sis-almacenamiento": { title: "Data paths", description: "Where Dax stores the database and models." },
  "sis-escritorio": { title: "This application", description: "Preferences that only affect the desktop client." },
};

const fields: Record<string, [label: string, description?: string, reason?: string]> = {
  "voice.enabled": ["Voice enabled", "Start the voice pipeline when Dax starts."],
  "voice.wake_word_model": ["Wake word", "openWakeWord model that wakes Dax, for example `hey_jarvis`."],
  "voice.denoise": ["Noise reduction", "Clean microphone audio before transcription."],
  "voice.adaptive_endpointing": ["Adaptive end of speech", "Adjust waiting time to your speaking rhythm instead of fixed silence."],
  "voice.silence_duration_ms": ["Silence before ending speech", "Milliseconds of silence before considering your utterance complete."],
  "voice.wake_word_threshold": ["Wake-word threshold", "Higher requires clearer pronunciation; lower may trigger by itself."],
  "voice.vad_threshold": ["Voice detection threshold", "Minimum energy considered speech. Raise it in noisy rooms."],
  "voice.barge_in": ["Interrupt while speaking", "Interrupt a response by speaking over it."],
  "voice.earcon": ["Status sounds", "Play a short tone when listening starts and ends."],
  "voice.voice_confirm": ["Spoken confirmations", "Ask aloud before tools marked `ask`."],
  "voice.require_wake_word_each_turn": ["Wake word on every turn", "Without this, Dax keeps listening during the follow-up window."],
  "voice.followup_activation_ms": ["Follow-up window", "How long Dax keeps listening after replying without another wake word."],
  "voice.conversation_timeout_s": ["End conversation after silence", "Seconds without speech before waiting for the wake word again."],
  "voice.thinking_pause_ms": ["Thinking pause", "Extra margin before ending an utterance when you pause mid-thought."],
  "voice.response_timeout_s": ["Maximum response time", "Abort the turn when the agent takes longer than this."],
  "voice.conversation_timeout_question_s": ["Conversation timeout after a question", "A longer wait when Dax has just asked you something."],
  "voice.session_ttl_minutes": ["Voice session lifetime", "Minutes to retain voice conversation context."],
  "voice.tts_engine": ["Speech engine", "Kokoro and Piper run locally; OpenAI is hosted and requires a key."],
  "voice.tts_kokoro_voice_es": ["Spanish Kokoro voice", "Kokoro voice ID for Spanish turns."],
  "voice.tts_kokoro_voice_en": ["English Kokoro voice", "Kokoro voice ID for English turns."],
  "voice.tts_kokoro_speed": ["Kokoro speed", "1.0 is natural speed. Values over 1.3 lose naturalness."],
  "voice.tts_voice_es": ["Spanish Piper voice", "Piper voice model for Spanish turns."],
  "voice.tts_voice_en": ["English Piper voice", "Piper voice model for English turns."],
  "voice.tts_openai_model": ["OpenAI voice model", "For example `gpt-4o-mini-tts`."],
  "voice.tts_openai_voice": ["OpenAI voice", "Voice name from the OpenAI catalog, for example `nova`."],
  "voice.tts_openai_instructions_es": ["Spanish tone instructions", "How the Spanish voice should sound: pace, energy, and character."],
  "voice.tts_openai_instructions_en": ["English tone instructions", "How the English voice should sound: pace, energy, and character."],
  "voice.tts_openai_timeout_s": ["Hosted synthesis timeout", "Seconds before abandoning the OpenAI request."],
  "voice.tts_fallback_to_local": ["Fall back to local voice", "Use the local engine if OpenAI fails."],
  "voice.stt_backend": ["Transcription engine", "Local uses faster-whisper; OpenAI sends audio to its API."],
  "voice.stt_model": ["Local model", "Whisper size: tiny, base, small, medium, or large-v3."],
  "voice.stt_language": ["Transcription language", "Set `es` or `en` for accuracy; `auto` detects each turn."],
  "voice.stt_openai_model": ["Hosted model", "For example `gpt-4o-transcribe` or `whisper-1`."],
  "voice.stt_openai_prompt": ["Vocabulary hint", "Names and jargon that hosted transcription often gets wrong."],
  "llm.openai.api_key": ["OpenAI API key", "Stored encrypted. Leave blank to retain the current key."],
  "voice.stt_fallback_to_local": ["Fall back to local transcription", "Use local Whisper if the API fails."],
  "voice.stt_openai_timeout_s": ["Hosted transcription timeout", "Seconds before abandoning the OpenAI request."],
  "voice.stt_compute_type": ["Compute precision", "int8 is fastest on CPU; float16 requires a GPU."],
  "voice.stt_device": ["Device", "Where Whisper runs. `auto` chooses a GPU when available."],
  "voice.stt_beam_size": ["Beam size", "1 is fastest. Higher values add per-turn latency for little gain."],
  "voice.speaker_verification": ["Verify speaker", "Compare each turn with your voice profile and reject other speakers."],
  "voice.speaker_fail_open": ["Allow when verification fails", "Let a turn through when the model errors instead of blocking it."],
  "voice.speaker_threshold": ["Similarity threshold", "Minimum similarity to your profile. Raise it if another voice passes."],
  "llm.default_provider": ["Default provider", "The first provider queried on every turn."],
  "llm.fallback_order": ["Fallback chain", "One provider per line. The router moves down the list after failures."],
  "llm.max_tools": ["Tools per turn", "A latency lever: too low hides servers; too high inflates the prompt."],
  "llm.max_tool_iterations": ["Tool iterations", "How many rounds of tool calls the agent may chain in one turn."],
  "llm.openai.model": ["Model", "For example `gpt-5.1` or `gpt-4o`."],
  "llm.openai.reasoning_effort": ["Reasoning effort", "Only sent on turns without tools because the API rejects it with functions."],
  "llm.openai.base_url": ["Base URL", "Change only to use an OpenAI-compatible proxy."],
  "llm.openai.timeout": ["Timeout", "Seconds before abandoning the request."],
  "llm.anthropic.model": ["Model", "For example `claude-sonnet-4-5`."],
  "llm.anthropic.api_key": ["API key", "Stored encrypted. Leave blank to retain the current key."],
  "llm.anthropic.timeout": ["Timeout", "Seconds before abandoning the request."],
  "llm.gemini.model": ["Model", "For example `gemini-2.5-pro`."],
  "llm.gemini.api_key": ["API key", "Stored encrypted. Leave blank to retain the current key."],
  "llm.gemini.timeout": ["Timeout", "Seconds before abandoning the request."],
  "llm.deepseek.model": ["Model", "For example `deepseek-chat`."],
  "llm.deepseek.api_key": ["API key", "Stored encrypted. Leave blank to retain the current key."],
  "llm.deepseek.base_url": ["Base URL", "DeepSeek API endpoint."],
  "llm.deepseek.timeout": ["Timeout", "Seconds before abandoning the request."],
  "llm.ollama.model": ["Model", "Name exactly as shown by `ollama list`."],
  "llm.ollama.base_url": ["Base URL", "Where Ollama listens. Default: http://localhost:11434."],
  "llm.ollama.timeout": ["Timeout", "Seconds before abandoning the request. Large local models take time."],
  "llm.codex.binary": ["Executable", "Path or binary name for Codex on PATH."],
  "llm.codex.model": ["Model", "Passed to `codex exec`; blank uses its default."],
  "llm.codex.timeout": ["Timeout", "Seconds before killing the subprocess."],
  "mcp.servers": ["MCP servers", "Dynamic collection: add, edit, reconnect, and authenticate with OAuth."],
  "tools.policy.default": ["Default decision", "Applied to any tool that matches no pattern."],
  "tools.confirm_timeout_seconds": ["Confirmation timeout", "If nobody answers in time, the tool is DENIED."],
  "tools.policy.allow": ["Allow", "One pattern per line. These run without asking."],
  "tools.policy.ask": ["Ask", "One pattern per line. These open a confirmation prompt."],
  "tools.policy.deny": ["Deny", "One pattern per line. These are always denied."],
  "tools.shell_allow": ["Binary list", "Saved through the shell-allow endpoint, separately from this section."],
  system_prompt: ["System prompt", "Blank is not accepted; use Restore to return to the Dax default."],
  memory_path: ["Memory folder", "Directory containing markdown memory files."],
  "telegram.enabled": ["Telegram enabled", "Start polling incoming messages."],
  "telegram.bot_token": ["Bot token", "Provided by @BotFather and stored encrypted."],
  "telegram.allowed_user_ids": ["Allowed IDs", "One numeric ID per line. Empty allows any Telegram user; set this list before enabling the bot."],
  "telegram.respond_with_audio": ["Reply with audio", "Send a voice note in addition to text."],
  "whatsapp.enabled": ["WhatsApp enabled", "Accept incoming messages from the Evolution webhook."],
  "whatsapp.evolution_api_url": ["Evolution API URL", "Where your Evolution instance runs."],
  "whatsapp.evolution_api_instance": ["Instance", "Instance name within Evolution."],
  "whatsapp.evolution_api_key": ["Evolution API key", "Stored encrypted. Leave blank to retain the current key."],
  "whatsapp.respond_with_audio": ["Reply with audio", "Send a voice note in addition to text."],
  "whatsapp.webhook_secret": ["Webhook secret", "Authenticate incoming Evolution calls to the WhatsApp webhook path."],
  "security.password_hash": ["Password", "Stored as an Argon2 hash through the password-change endpoint."],
  "security.auth_enabled": ["Require login", "Disabling this leaves the API open to anything that can reach the port."],
  "security.session_ttl_hours": ["Session lifetime", "Hours before sign-in is required again."],
  "security.device_token_ttl_minutes": ["Device token lifetime", "How long a mobile access token remains valid.", "The configuration API does not accept changes to this value yet."],
  "security.pairing_code_ttl_minutes": ["Pairing code lifetime", "How long a new-device pairing code remains valid.", "The configuration API does not accept changes to this value yet."],
  "security.cookie_secure": ["Secure cookie", "Requires HTTPS. Leave off for plain HTTP loopback."],
  "security.cookie_name": ["Cookie name", "Name of the signed session cookie."],
  "security.session_secret": ["Session signing secret", "Key used to sign cookies. Changing it ends every session.", "Managed by encrypted storage; the backend neither exposes it nor accepts it via PATCH."],
  "web.host": ["Listen address", "127.0.0.1 keeps it local; 0.0.0.0 exposes it to the network."],
  "web.port": ["Port", "Backend TCP port."],
  "web.expose_lan": ["Expose to local network", "Allow other machines on your network to reach Dax."],
  "web.cors_origins": ["CORS origins", "One origin per line. The desktop app uses tauri://localhost."],
  "web.dev_mode": ["Development mode", "Add http://localhost:5173 to allowed origins."],
  name: ["Assistant name", "How Dax introduces itself."],
  language_default: ["Default language", "Used when a channel does not specify one."],
  log_level: ["Log level", "Detail level for messages shown in the log viewer."],
  "storage.database_path": ["Database", "SQLite database for conversations, tool audit, and encrypted secrets.", "The backend displays this path but provides no PATCH route; it is fixed at install time."],
  "storage.models_path": ["Models", "Folder containing voice and speaker-profile models.", "The backend displays this path but provides no PATCH route; it is fixed at install time."],
};

const optionLabels: Record<string, string> = {
  alojado: "hosted", subproceso: "subprocess", Permitir: "Allow", Preguntar: "Ask",
  Rechazar: "Deny", "Detectar automáticamente": "Detect automatically", Español: "Spanish", Inglés: "English",
};

function localizeField(field: FieldSpec): FieldSpec {
  const text = field.key ? fields[field.key] : undefined;
  return {
    ...field,
    label: text?.[0] ?? field.label,
    description: text?.[1] ?? field.description,
    reason: text?.[2] ?? field.reason,
    options: field.options?.map((option) => ({
      ...option,
      label: Object.entries(optionLabels).reduce((label, [from, to]) => label.replace(from, to), option.label),
    })),
  };
}

export function localizeRegistry(source: SectionSpec[]): SectionSpec[] {
  return source.map((section) => ({
    ...section,
    ...sections[section.id],
    groups: section.groups.map((group) => ({
      ...group,
      ...groups[group.id],
      fields: group.fields.map(localizeField),
    })),
  }));
}
